\newlabel{alg:iou_alg}
\newlabel{eqn:10}
\newlabel{eqn:1}
\newlabel{eqn:2}
\newlabel{eqn:3}
\newlabel{eqn:4}
\newlabel{eqn:5}
\newlabel{eqn:6}
\newlabel{eqn:7}
\newlabel{eqn:8}
\newlabel{eqn:cluster}
\newlabel{fig:arch}
\newlabel{fig:bgmethod}
\newlabel{fig:cnn}
\newlabel{fig:cpu}
\newlabel{fig:encoder}
\newlabel{fig:gpu}
\newlabel{fig:iou}
\newlabel{fig:macroblock}
\newlabel{fig:mvanalysis}
\newlabel{fig:mvextract}
\newlabel{fig:mvobject}
\newlabel{fig:mv}
\newlabel{fig:network}
\newlabel{fig:noise}
\newlabel{fig:objectdetect}
\newlabel{fig:objecttracking}
\newlabel{fig:opticalflow}
\newlabel{fig:overall}
\newlabel{fig:proposedMethod}
\newlabel{fig:smoke}
\newlabel{fig:sysdesign}
\newlabel{fig:testbed}
\newlabel{fig:va_arch}
\newlabel{fig:va_a}
\newlabel{fig:va_b}
\newlabel{fig:yolov3}
\newlabel{fig:yolo}
\newlabel{fig:yuv420}
\newlabel{sub:filter}
\newlabel{sub@fig:va_a}
\newlabel{sub@fig:va_b}
\newlabel{subsec:1}
\newlabel{subsec:frameworks}
\newlabel{tab:computingresource}
\newlabel{tab:hw}
\newlabel{tab:motiontime}
\newlabel{tab:timemessasure}
\newlabel{tab:videotest}
\newlabel{tab:videotest}
